spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      #删除access-key和secret-key 不传到git上
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: gulimall-luodong


  application:
    name: bootsystem-third-party

server:
  port: 30000
